# Generated by Django 6.0.2 on 2026-02-26 06:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sxcmodel', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quizattempt',
            options={'ordering': ['-final_grade']},
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='current_section_index',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='useranswer',
            name='time_taken_seconds',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='useranswer',
            unique_together={('attempt', 'question')},
        ),
        migrations.CreateModel(
            name='Leaderboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('final_grade', models.FloatField(db_index=True)),
                ('raw_score', models.FloatField()),
                ('correct_count', models.IntegerField()),
                ('incorrect_count', models.IntegerField()),
                ('total_time_seconds', models.IntegerField()),
                ('achieved_at', models.DateTimeField()),
                ('attempt', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='leaderboard_entry', to='sxcmodel.quizattempt')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='leaderboard_entry', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-final_grade'],
            },
        ),
    ]
