# Generated by Django 6.0.2 on 2026-02-11 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailyquiz',
            old_name='question',
            new_name='questions',
        ),
        migrations.AlterField(
            model_name='question',
            name='last_appeared',
            field=models.DateField(blank=True, null=True),
        ),
    ]
