# Generated by Django 6.0.2 on 2026-02-22 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_email_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='useronboarding',
            name='updates_opt_in',
            field=models.BooleanField(default=False),
        ),
    ]
