# Generated by Django 6.0.2 on 2026-02-24 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_useronboarding_updates_opt_in'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useronboarding',
            name='primary_purpose',
            field=models.CharField(choices=[('daily_quiz', 'Solving Daily Questions'), ('discussion', 'Engaging in Discussion Forums'), ('sxc_model_set', 'Checking Out Model Set'), ('book_info', 'Learning More About the Book'), ('all', 'Making Complete Use of the Website'), ('other', 'Other')], max_length=100),
        ),
    ]
