# Generated by Django 6.0.2 on 2026-02-24 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_useronboarding_primary_purpose'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useronboarding',
            name='how_discovered',
            field=models.CharField(choices=[('official', 'Official Book'), ('google', 'Google Search'), ('facebook', 'Facebook'), ('instagram', 'Instagram'), ('friend', 'Friend / Teacher'), ('other', 'Other')], max_length=100),
        ),
    ]
