# Generated by Django 6.0.2 on 2026-03-10 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_useronboarding_how_discovered_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useronboarding',
            old_name='updates_opt_in',
            new_name='newsletter_opt_in',
        ),
        migrations.AlterField(
            model_name='useronboarding',
            name='complete_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
