# Generated by Django 6.0.2 on 2026-02-24 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_useronboarding_how_discovered_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useronboarding',
            name='how_discovered',
            field=models.CharField(choices=[('official', 'Official Book'), ('google', 'Google Search'), ('facebook', 'Facebook'), ('instagram', 'Instagram'), ('friend', 'Friend / Teacher'), ('other', 'Other')], max_length=100),
        ),
        migrations.AlterField(
            model_name='useronboarding',
            name='primary_purpose',
            field=models.CharField(choices=[('daily_quiz', 'Daily Questions'), ('discussion', 'Engaging in Discussion'), ('sxc_model_set', 'Checking Model Set'), ('book_info', 'Learn More About Book'), ('all', 'Everything'), ('other', 'Other')], max_length=100),
        ),
    ]
