# Generated by Django 6.0.2 on 2026-03-11 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_passwordresettoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='deletionotp',
            name='attempt_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
